version: '3.9'
services:
  app:
    build:
      context: ./../../
      dockerfile: './deployments/background/build.Dockerfile'
      target: PRODUCT
    container_name: 'background_application'
    env_file:
      - secret.env
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - "mysql"
  mysql:
    image: 'mysql:8'
    ports:
      - '3306:3306'
    container_name: 'background_mysql'
    restart: on-failure
    env_file:
      - secret.env
    volumes:
      - './schema.sql:/docker-entrypoint-initdb.d/1.sql'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
