version: '3.9'
services:
  app_test:
    build:
      context: ./../../
      dockerfile: './deployments/background/build.Dockerfile'
      target: TEST
    container_name: 'background_application_test'
    env_file:
      - secret.env
    depends_on:
      mysql_test:
        condition: service_healthy
    links:
      - "mysql_test:mysql"
  mysql_test:
    image: 'mysql:8'
    ports:
      - '3306:3306'
    container_name: 'background_mysql_test'
    env_file:
      - secret.env
    volumes:
      - './schema.sql:/docker-entrypoint-initdb.d/1.sql'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
